boot.spring.io.debezium.DebeziumClusterClientAutoConfiguration=
boot.spring.io.debezium.DebeziumKafkaClientAutoConfiguration=
boot.spring.io.debezium.DebeziumPulsarClientAutoConfiguration=
boot.spring.io.debezium.DebeziumRabbitmqClientAutoConfiguration=
boot.spring.io.debezium.DebeziumRocketmqClientAutoConfiguration=
boot.spring.io.debezium.DebeziumSimpleClientAutoConfiguration=
